Add-mcc-page
bongloy/bongloy-terms pull request #2
Opened 2018-05-02 10:15 UTC by khomsovon

## Add high risk mcc categories page
- Implement high risk mcc categories in Bongloy term renderer
- Create markdown kh_high_risk_mcc_categories file
- Update spec for high risk mcc categories

2018-05-09 03:12 UTC, samnang commented on lib/bongloy/terms/renderer.rb
> +
```rb
def render(page, country: :kh, locale: :en)
  markdown.render(File.read(path_to_root("#{country}_#{page}.#{locale}.md")))
end
```

2018-05-09 03:33 UTC, measoutdam commented
## Todo:

- [ ] Read me - Add MCC link [screen](https://cl.ly/3J0v1r3N280k)
- [ ] Read me - Update usage [screen](https://cl.ly/2j1H1W14441W)
- [ ] lib/../terms.rb : refactor with public method [feedback](https://cl.ly/2n2Z1m2u0z23)
- [ ] lib/../terms.rb : `do_render?` is not required
- [ ] lib/../terms.rb: reorder private methods [screen](https://cl.ly/0K2M2q0e1I3c)

2018-05-12 15:25 UTC, samnang requested changes

2018-05-12 15:25 UTC, samnang commented on spec/bongloy/terms/renderer_spec.rb
>    include EnvHelpers
we don't need this anymore because we do anything with environment variables.

2018-05-12 15:25 UTC, samnang commented on spec/bongloy/terms/renderer_spec.rb
> +    it { expect(subject.render('fees_taxes')).to be_a(String) }
How about remove everything and has only one line per page.

```rb
describe Bongloy::Terms::Renderer do
  it { expect(subject.render('terms')).to be_a(String) }
  it { expect(subject.render('privacy')).to be_a(String) }
  it { expect(subject.render('prohibited_businesses')).to be_a(String) }
  it { expect(subject.render('high_risk_mcc_categories')).to be_a(String) }
  it { expect(subject.render('fees_taxes')).to be_a(String) }
end
```

2018-05-20 17:07 UTC, samnang approved these changes

2018-05-20 17:09 UTC, merged